src/app/address/controllers/addressResults.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/locales/en/default.yml
src/locales/en/pages.yml
src/views/address/results.html

**NB please review: [KBV-172](https://github.com/alphagov/di-ipv-cri-address-front/pull/20)**  first
Added a small UI change to display the searched postcode with a link to revert back a page and change their search query. A resulting test case for setting session variable was also added.
To allow users to change their postcode after doing a search, we should add a change postcode link to directly back to the page they've come from. 
- [KBV-64](https://govukverify.atlassian.net/browse/KBV-64)

KBV-64-add-change-postcode-link

---

src/app/address/fields.js
src/locales/en/default.yml

Add validation rules to postcode input and placeholder content for those errors for the time being.
No validation on input currently.
- [KBV-186](https://govukverify.atlassian.net/browse/KBV-186)
Handled by the form wizard

KBV-186-add-validation-to-postcode-input

---

src/app/address/controllers/address.js
src/app/address/steps.js
src/locales/en/default.yml
src/views/address/results.html

We should allow users to enter their address manually in the event they are unable to find their address in the response.
Added a hyperlink to the address view in the results view. Also modified the steps to allow the user to jump from the address to the confirmation page, permitting they had come from address.
This change allows users to add their address manually when they cant find their address in the postcode response.
- [KBV-171](https://govukverify.atlassian.net/browse/KBV-171)

KBV-171-add-address-not-found-link

---

src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/app/address/steps.js
test/application/features/address.feature
test/application/pages/address.js
test/application/step_definitions/address.js
test/mocks/mappings/addresses.json

Address search should not throw an error when the Postcode API returns an error. Instead it should direct the user to the address confirmation page.
We allow the diverging paths by using the HMPO Form wizards conditional steps. By setting a variable called `isSuccessful` and setting that variable to false in an unsuccessful instance we can then direct the user journey to the address entry page rather than address results.
[HMPO-form-wizard docs for the step condition.](https://github.com/HMPO/hmpo-form-wizard#:~:text=%7B%20field%3A%20%27field1%27%2C%20op%3A%20(fieldValue%2C%20req%2C%20res%2C%20con)%20%3D%3E%20fieldValue%20%3D%3D%3D%20con.value%2C%20value%3A%20true%2C%20next%3A%20%27next%2Dstep%27%20%7D%2C)
Next iteration could be depending on the return code, do we pop up an error saying …

Kbv 201 handle error from postcode lookup

---

.github/workflows/checks.yml

Add missing env for sonarcloud integration

BAU-fix-github-sonar-scan-pipeline

---

src/lib/config.js

Introduced a tiny bug with the redirect path that meant the redirect was going to the wrong place after session logged. This will correct it.

bugfix: correct app source path

---

README.md
package.json
src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/controllers/addressResults.js
src/app/address/controllers/addressResults.test.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/app/oauth2/middleware.js
src/lib/axios.js
src/lib/config.js
test/browser/pages/result.js
test/browser/step_definitions/address.js
test/data/testData.js
test/mocks/mappings/addresses.json
test/utils/addressFactory.js
test/utils/mocha-helpers.js

- call postcode api with session header and the postcode rather than the ordnance survey directly.
- session header correction.
- Browser tests and unit test refactor.
- refactor the Axios instance creation.
- Update readme
Now we've move the postcode lookup to the backend we should use it.
This provides an additional layer of security in managing the postcode api secrets.
With this change we need to update the browser tests, the unit tests, the readme and the created axios instances.
- [KBV-275](https://govukverify.atlassian.net/browse/KBV-275)

Kbv 275 move postcode lookup to be

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/lib/config.js
src/views/address/confirm.html
test/browser/features/address-previous.feature
test/browser/pages/confirm.js
test/data/testData.js
test/mocks/mappings/addresses.json
test/utils/mocha-helpers.js

Now we have a backend to send addresses too, we can now point the Frontend to the backend. This makes the relevant changes.
Temporarily I've paused the addition of adding previous addresses as the work to finalise the designs and content is still underway. 
For the time being I'm just rendering the JSON block onto the screen. A separate PR will be created to complete the redirect to the stub. This is to keep the PR's small enough to review quicker.
This is part of the work for the address CRI happy path.
- [KBV-285](https://govukverify.atlassian.net/browse/KBV-285)

KBV 285 call address api from frontend

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/steps.js
src/app/oauth2/index.js
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/lib/config.js

Added a redirection after the addresses have been saved.
We should redirect back to callback URL with the auth code and state.
- [KBV-294](https://govukverify.atlassian.net/browse/KBV-294)

KBV-294-redirect-to-callback-url

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

Migration to private JWT as referenced [here](https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0018-ipv-generic-frontend-cri-interface.md). The frontend needs to just pass the client_id and the jwt from core to the backend.
This has been changed because the JWT could container personally identifiable information. Therefor the JWT coming from core must be encrypted.
- [KBV-306](https://govukverify.atlassian.net/browse/KBV-306)

feature: Pass signedJWT to API

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js

Test fix for the saveValues. 
SaveValues function signature is incorrect. As a result of async hell, test would "pass" but they're not actually testing anything.
Fixing false positive tests.

BAU-test fix for confirmAddress-saveValues signature is incorrect

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/oauth2/middleware.js

Save the redirect url with the token response then redirect to it at the end of the journey
The redirect URL is embedded within the encrypted JWT, so the frontend will receive a URL from the BE after the JWT has been decrypted.
- [KBV-343](https://govukverify.atlassian.net/browse/KBV-343)

KBV-343-handle-redirect-url

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/controllers/addressResults.test.js
src/app/address/controllers/addressSearch.js
test/utils/addressFactory.js

Address model references to postalTown changed to addressLocality and postcode changed to postalCode
To match changes made on the backend
Food for thought, this would be easier to track had we used Typescript. Thankfully the overall size of this work is fairly small so impact is small.
- [KBV-351](https://govukverify.atlassian.net/browse/KBV-351)

KBV-351-Update-address-model

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/address/confirm.html

changes to the design of the address confirm page to use the govuk summary component.
These changes are in a list of design changes. Additional logic changes are to come.
Align with design changes.
- [KBV-366](https://govukverify.atlassian.net/browse/KBV-366)

KBV-366-update-address-confirm-page

---

test/browser/.env.sample
test/browser/README.md
test/browser/compose.yml
test/browser/cucumber.js
test/browser/di-ipv-config.yaml
test/browser/support/setup.js
test/mocks/mappings/addresses.json

This uses a Docker image to spin up a locally configured core-stub with a wiremock server and an address-front from a local Dockerfile.
The mocked data has been adjusted to match live data so that the tests can be run against live or mocked data transparently.
- Added a docker-compose configuration
- Added config for standalone core-stub
- Changed urls to use environment variables
- 
- [KBV-336](https://govukverify.atlassian.net/browse/KBV-336)

[KBV-336] Restore mocked browser tests

---

src/locales/en/default.yml
src/locales/en/fields.yml
src/views/address/search.html

Align search page with designs. Need to override the form main content for the custom text on the buttons.
Align with design
- [KBV-367](https://govukverify.atlassian.net/browse/KBV-367)

KBV-367-update-search-page-to-align-with-design

---

src/app/address/fields.js
src/app/address/validators/postcodeValidator.js
src/app/address/validators/postcodeValidator.test.js
src/locales/en/default.yml

Add formatting rules for postcode
Added validation rules for postcode entry.
We need to include user friendly postcode error messaging. 
- [KBV-368](https://govukverify.atlassian.net/browse/KBV-368)

KBV-368-update-error-handling-for-postcodes

---

src/locales/en/default.yml

Content change for missing postcode validation message from `a` to `your`
Slight change in content to match the designs.

BAU-slight-change-in-content-for-missing-postcode-validation

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/app/address/fields.js
src/app/address/steps.js
src/app/address/validators/addressValidator.js
src/app/address/validators/addressValidator.test.js
src/locales/en/default.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/address/address.html
src/views/address/search.html

Add validation rules to the manual address page.
In this PR, it is mostly validation rules being added alongside tests. I also took the opportunity to do a tiny refactor of a variable name that was using snake case rather than camelCase... I suspect I may do more of that in the future.
To reduce the number of mistakes when adding an address to the store, we've added a number of validation methods to stop the user when they're adding their details. 
- [KBV-371](https://govukverify.atlassian.net/browse/KBV-371)

KBV 371 add validation to manual address fields

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

There were a few oauth tests that weren't running correctly. This refactor adds extra error handling, and fixes the tests to handle the range of cases.

tests: Fix redirects with missing values

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js

Moving from current address to previous address we should reset the search value to show the user an empty address search page. 
Makes it clearer to the user that they're entering a new address journey

BAU: remove existing search value from session when entering the previous journey

---

src/views/address/templates/address-base.html

Updated the template to include the backlink to the form
This was accidentally removed when the template was created.

BAU-add-backlink-to-template

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/steps.js
src/views/address/confirm.html

hooked up links to allow users to modify their addresses.
As part of the changes, I refactored how address view knows what address to pre-populate its fields. If the origin URL is a previous URL we should use the users previous address, else use the users current address or if they've arrived from the result page, use the chosen address.
Design allow users to go back and change their address. These links needed to be hooked up to their relative steps.

BAU-Hook up the edit links across address views

---

src/app/address/controllers/addressConfirm.js
src/app/oauth2/middleware.js
src/lib/oauth.js
src/lib/oauth.test.js

The storing of `oauth` related properties, and the generation of the `redirect_url` have been extracted into their own library.
This should make it easier to replace them with one that works on the session, and make it easier to move into a more common usage.
- [KBV-397](https://govukverify.atlassian.net/browse/KBV-397)

Refactor oauth props

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/lib/oauth.js
src/lib/oauth.test.js

OAuth params are now stored on the `req.session.authParams` object, instead of the `req.sessionModel`. This makes it more flexible and easier to use in a common way.
- [KBV-397](https://govukverify.atlassian.net/browse/KBV-397)

refactor: Move oauth properties from sessionModel to session.authParams

---

src/locales/en/default.yml

Cannot find address URL was incorrectly moving to a /edit url when the user hasn't been to part of the journey yet.
caused a bug when the user couldnt find their address

Bugfix: Can't find address URL is incorrectly referencing and /edit step.

---

src/app.js
src/app/oauth2/index.js
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/lib/axios.js
src/lib/axios.test.js
src/lib/settings.js
src/lib/settings.test.js

This is a bit of a big PR, but it is doing one thing - refactoring common code to use properties set via `express` `app.set('propertyname','propertyvalue')`.
The code to do set these properties can be invoked during server creation, as per `settings.js`.
At this point, all the code in `/app/oauth` can be moved into a common area.  All the code in `lib`, except for `config` and `settings` can also be moved over. These two files will be different for each credential issuer.
Missing tests have also been added.
Any thoughts on naming are welcome.
- [KBV-397](https://govukverify.atlassian.net/browse/KBV-397)

refactor: Use common config with express app.set / app.get

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/locales/en/default.yml
src/locales/en/pages.yml
src/views/address/components/address-input-fields.html
src/views/address/components/address-year-from-field.html
test/utils/mocha-helpers.js

Migration from GovUK components to hmpoComponents. This resulted in a extending getValues instead of locals in the wizard journey so that we could auto fill the components.
GOVUK components don't directly inherit the validation design functionality that HMPO components have. As a result we're missing some design aspects of the GovUK design systems.
Rather than implement our own, we should go full in and use HMPO Components for full functionality. This required a change to use `getValues` instead of `locals` which makes more sense in hmpo-form-wizard journey. As locals shouldn't; be used to represent data that is about to be saved, in this situation.

BAU refactor to use HMPO Components over GovUK components 

---

src/locales/en/default.yml

Standardise the validation messages to match the framework by including `.`

BAU-minor-content-refinement

---

src/app/address/controllers/addressResults.js
src/app/address/controllers/addressResults.test.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/app/address/fields.js
src/app/address/steps.js
src/locales/en/fields.yml
src/views/address/components/address-results-field.html
test/utils/mocha-helpers.js

- Added validation to address results dropdown.
- Refactor variable name to camelCase 
This is additional validation for the results page, to stop users from clicking the default message accidentally.
- [KBV-436](https://govukverify.atlassian.net/browse/KBV-436)

Kbv 436 add validation to results drop down

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressSearch.js
src/app/address/presenters/addressPresenter.js
src/app/address/presenters/addressPresenter.test.js

Part 2 of additional address fields being missed.
Address fields are being missed from view and then not saved in the VC. This is because we lose concept of the address fields when moving from results to address to confirm. This PR makes sure the address retains fields not show (this is a separate issue) and then displays them correct in the confirmation page.
If any additional edits are made the address, we delete the UPRN. This is to stop someone from modifying the address but retaining the UPRN and potentially showing incorrect data in the VC.
- [KBV-404](https://govukverify.atlassian.net/browse/KBV-404)

KBV-404-Building-name-clipped-confirm-page

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/fields.js
src/app/address/steps.js
src/app/address/validators/confirmationValidator.js
src/app/address/validators/confirmationValidtor.test.js
src/locales/en/fields.yml
src/views/address/confirm.html

I refactored the radio button into hmpo radios, by doing this I was also able to add validation for the radio button.
Refactoring also fixed the bug in the ticket and reduced code. 
Regardless of what the user choose, the wizard always took them to the previous address journey
- [KBV-509](https://govukverify.atlassian.net/browse/KBV-509)

KBV-509-Confirmation-radio-button-always-pushed-user-to-previous-address-journey

---

README.md
package.json
src/views/address/confirm.html
test/browser/features/address-confirm.feature
test/browser/pages/address.js
test/browser/pages/confirm.js
test/browser/step_definitions/confirm.js

Adding confirmation page browser tests for behaviour of going back and changing address details, confirming those changes.
Does not test going to the next step and exchanging access token etc.
Tidy up of the browser tests + adding new ones.

BAU-update-browser-tests-confirm-page

---

src/views/address/results.html
src/views/previous/results.html
test/browser/features/address-results-previous.feature
test/browser/features/address-results.feature
test/browser/pages/result.js
test/browser/step_definitions/results.js

Change the template to overwrite the mainContent block instead of the whole contentBlock. This results in the error summary being shown.
Also added additional browser tests.
This was one of the flags the accessibility audit.
- [KBV-580](https://govukverify.atlassian.net/browse/KBV-580)

KBV-580-Add-error-summary-component-to-results-page

---

src/app/address/controllers/address/results.js
test/browser/features/address-results-previous.feature
test/mocks/mappings/addresses.json

A validation on same address appearing twice was broken after I merged a refactor of the wizards.
This fixes a bug inside the validation of same address.
- [KBV-586](https://govukverify.atlassian.net/browse/KBV-586)

KBV-586 validation on same address is not showing

---

deploy/template.yaml

frontend instances should scale when there is high traffic load
Add autoscaling for production environment
Currently this will only scale to a max of 3 containers. 
Performance scaling required in production.

ECS: add ecs autoscaling for production

---

deploy/template.yaml
package.json
src/app.js
src/lib/config.js
yarn.lock

Updated Address front to use express-session and dynamodb-connect to store the front-end session details within an aws DynamoDB table.
To have persistant storage method for the front-end data that is in line with the rest of the programme and means we can avoid setting up and managing a Redis cluster as the alternative.
- [KBV-608](https://govukverify.atlassian.net/browse/KBV-608)

KBV-608: Update address-front to connect to DynamoDB for its session storage

---

src/views/address/address.html
src/views/address/search.html
src/views/previous/address.html
src/views/previous/search.html

gtmJourneys were incorrectly reversed on two pages.
This is causing Google Analytics to be confused.

fix: Use correct gtmJourney

---

src/app.js
src/lib/config.js

**testing** This is hard to test locally as we don't actually connect to dynamo db. We could spin up a local dynamo db table. However, I think just merging this small change and testing in build/stage could suffice. 
Added a Session TTL variable and allowed it to be overwritten by a process environment variable. Set the default to 720000 which is two hours in ms.  If we can confirm this works, then we should think about setting it in the common express somehow.
The session is currently defaulting to 1 day, which is set in the library connect-dynamodb.
It appears that that's the default because no maxAge is supplied. From the express documentation, we just need to add maxAge properties to the options which are passed into express in the hmpo-app.
See - …

KBV-683-add-session-ttl

---

deploy/template.yaml

Removed redis from frontend deployment
The frontend is now using DynamoDB instead of Redis
- [OJ-674](https://govukverify.atlassian.net/browse/OJ-674)
The Redis environment variable has been removed from the deployment
In memory Redis is remaining fo testing purposes

OJ-674 remove redis from frontend

---

deploy/template.yaml

To get the frontend to 2 instances, I suspect we need to set this value to 2 to allow for a second instance. To keep the scaling size the same, I've increased the maximum as well.
To set a min of two instances for the FE
- [OJ-878](https://govukverify.atlassian.net/browse/OJ-878)

OJ-878-set-instances-to-2

---

src/app/address/controllers/summary/confirm.js
src/app/address/controllers/summary/confirm.test.js

Bugfix: stop addresses being saved when no address found
There is a usecase is causing the address frontend to send an empty array to be saved. This causes our backend to throw an error.

Bugfix-stop-empty-address-being-saved

---

deploy/template.yaml

Add both old non python and new python subscription filters for splunk
Requirement to use the new python subscription filters but to keep the old filters to ensure no logs get lost
- [OJ-985](https://govukverify.atlassian.net/browse/OJ-985)

OJ-985 update logging subscription filters

---

src/app/address/controllers/address/search.js
src/app/address/controllers/address/search.test.js
src/app/address/controllers/summary/confirm.js
src/app/address/controllers/summary/confirm.test.js
test/mocks/mappings/addresses.json
test/mocks/mappings/authorization-error.json

There is currently an inconsistency with the common API endpoints - some of them use `session-id` and some of them use `session_id`.
In order to non-breaking refactoring on the API - all the API requests will temporarily provide both parameters. Once the refactoring is complete, the unused parameter can be removed.
- [OJ-962](https://govukverify.atlassian.net/browse/OJ-962)

refactor: Send session_id & session-id for BE refactoring

---

src/app.js
src/views/address/results.html
src/views/components/address-input-fields.html
src/views/components/address-problem-field.html
src/views/components/address-year-from-field.html
src/views/previous/results.html
src/views/summary/confirm.html

Switch from using hmpo-i18n to i18next so that we can take advantage of cookie domains and interpolation.
This PR uses the i18next middleware exported from common-express, and updates templates with the minimal changes required to use the new library.
It does not contain any of the cookie domain or interpolation features.
It requires [common-express #109](https://github.com/alphagov/di-ipv-cri-common-express/pull/109) to be merged first, and the temporary dependency commit to be dropped.
- [OJ-913](https://govukverify.atlassian.net/browse/OJ-913)

Oj 913/use i18next

---

package.json
src/app.js
yarn.lock

Update setI18n call to pass through the main `router` not  the `app` so that middleware can be attached correctly.
This should fix the issue with the "missing" translation key.

Use router instead of app with i18next

---

package.json
src/app/address/controllers/address/manual.js
src/app/address/controllers/address/manual.test.js
src/presenters/addressPresenter.js
src/presenters/addressPresenter.test.js
test/browser/features/address-manual-rfc-0020-address-structure-compliance.feature
test/mocks/mappings/addresses.json

✅ Ensure that flat number is displayed and is editable in Address CRI
✅ Fix incorrect mapping and ordering of some fields when displaying an address
✅ Check that we don't break anything by checking the addresses mentioned in [RFC 0020 Address Structure](https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0020-address-structure.md#4-examples-of-json) display correctly.
To test yourself, please first merge https://github.com/alphagov/di-ipv-cri-address-front/pull/429, then:
* run `yarn install`
* run `yarn start:local:all`
* visit http://localhost:5010
* use postcode `ZZ1 1ZZ`
* choose the `MILTON KEYNES` address
* note that the flat number is displayed on edit and on the confirm page
* note that you can test the addresses mentioned in [RFC 0020 Address …

OJ-989 Map flat number from API field subBuildingName

---

package.json
src/app/address/controllers/address/manual.js
src/app/address/controllers/address/manual.test.js
src/presenters/addressPresenter.js
src/presenters/addressPresenter.test.js
test/browser/features/address-manual-rfc-0020-address-structure-compliance.feature
test/mocks/mappings/addresses.json

ℹ️  Reverts alphagov/di-ipv-cri-address-front#432
✅ Ensure that flat number is displayed and is editable in Address CRI
✅ Fix incorrect mapping and ordering of some fields when displaying an address
✅ Check that we don't break anything by checking the addresses mentioned in [RFC 0020 Address Structure](https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0020-address-structure.md#4-examples-of-json) display correctly.
To test yourself, please first merge https://github.com/alphagov/di-ipv-cri-address-front/pull/429, then:
* run `yarn install`
* run `yarn start:local:all`
* visit http://localhost:5010
* use postcode `ZZ1 1ZZ`
* choose the `MILTON KEYNES` address
* note that the flat number is displayed on edit and on the confirm page
* note that you can test the …

OJ-989 Un-revert edition: Map flat number from API field subBuildingName

---

.secrets.baseline
src/app/address/routes/sharedFields.js
src/presenters/addressPresenter.js
src/presenters/addressPresenter.test.js
test/browser/features/address-manual-empty-previous.feature
test/browser/features/address-manual-empty.feature

Set the Street Name to optional on the address frontend screen. This will then allow the user to perform the address-cri journey without entering a street name. Thus the use case in which the user is staying on a location (such as a farm) without a street name will pass.
- [OJ-991](https://govukverify.atlassian.net/browse/OJ-991)

OJ 991 - Make Street name optional on Address journey

---

deploy/template.yaml

Three CloudWatch alarms for the Address CRI frontend hosted on ECS. Alarm when:
1. ECS tasks lower than 1 over 2 minutes - there are no tasks running
2. ECS tasks lower than 2 over 15 minutes - there should be two tasks running
3. More than 1 ELB 5XX error every minute over 5 minutes 
- [OJ-1012](https://govukverify.atlassian.net/browse/OJ-1012)

OJ-1012 Address frontend alarms

---

deploy/template.yaml

Removed old log group subscription filters.
As requested by @instantiator
- [OJ-1015](https://govukverify.atlassian.net/browse/OJ-1015)

OJ-1015 - remove old log group subscription filter

---

test/browser/features/address-manual-rfc-0020-address-structure-compliance.feature
test/browser/features/flat-number.feature
test/browser/pages/confirm.js

Adding browser tests.
Minor change to how we get the confirmed details address. We changed it to inner html so that we can confirm the order of the address output is how we expect.
For example previously we would get the following value from playwright.
`1 115myroad mylocation`
now
`1 <br>my road<br> my location`
This means we can different styles of addresses outputs.
Adding browser tests for Address flat number change - https://govukverify.atlassian.net/browse/OJ-989
- [OJ-1006](https://govukverify.atlassian.net/browse/OJ-1006)

OJ-1006 testing flat number on edit

---

README.md

This link typo, somewhat to my surprise has broken the team manual.
Turns out the slight misformatting in the markdown is getting slurpped up by the team manual for [pages like
this](https://di-team-manual.london.cloudapps.digital/code/di-ipv-cri-address-front/index.html#di-ipv-cri-address-front).
Which in turn is then getting checked with html-proofer. Which reports the markdown error as a bad link and errors.
This means the team manual isn't building and can't be deployed.
This is a bit of an odd situation. Quick fix is to amend the markdown here. But I think in the long run we should stop html-proofer from checking everyone's README pages, if they're broken that should be down to teams to fix!
See [1] & [2]
[1]: https://gds.slack.com/archives/CAC6S0UHK/p1667583411670329
[2]: …

BAU: Fix link in readme markdown

---

src/app/address/controllers/address/prepopulate.js
src/app/address/controllers/address/prepopulate.test.js
src/app/address/controllers/address/search.js
src/app/address/controllers/address/search.test.js
src/locales/cy/pages.yml
src/locales/en/pages.yml
src/views/address/search.html
test/browser/features/address-with-prepopulated-postcode.feature
test/browser/pages/search.js
test/browser/step_definitions/search.js
test/browser/support/setup.js
test/mocks/mappings/pre-populated-postcode.json

Add prepopulated address to address lookup screen.
Driving licence callout should only be present until the user moves off the address search screen. After that, the postcode is considered to have been entered by the user.
- [OJ-941](https://govukverify.atlassian.net/browse/OJ-941)

Oj 941/build UI for partial address

---

src/locales/cy/default.yml
src/locales/en/default.yml

The product name is being changed from **GOV.UK Account** to **GOV.UK One Login**. The code in this PR updates any appearance of the name in the source code, including content which may be hidden from the user (e.g the cookie banner).
`locales/en/default.yml` and `locales/cy/default.yml` have been updated. **Do not merge** these changes until Thursday 9th February.
The user should see a consistent name for the service throughout their journey.
- [PYIC-2282](https://govukverify.atlassian.net/browse/PYIC-2282) - a subticket of [PYIC-2249](https://govukverify.atlassian.net/browse/PYIC-2249) for the journey-wide epic.
[PYIC-2282]: https://govukverify.atlassian.net/browse/PYIC-2282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PYIC-2249]: …

PYIC-2249 Update service name

---

deploy/template.yaml

Added export of the load balancer ARN
This allows the WAF pipeline deployment to reference the load balancer ARN for the web ACL association for the front end
- [OJ-1103](https://govukverify.atlassian.net/browse/OJ-1103)
[OJ-1103]: https://govukverify.atlassian.net/browse/OJ-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

oj-1103 address front exported load balancer arn

---

test/browser/features/address-confirm.feature
test/browser/features/address-manual-empty-previous.feature
test/browser/features/address-manual-preselected-previous.feature
test/browser/features/address-results-previous.feature
test/browser/features/address-search-previous.feature

Shift test to using 2023 instead of 2022
We have a 3-month window for calculating showing the previous address screen. 1 April is 3 months after 1 January, so tests started failing.

fix: Update tests with year of 2023

---

src/locales/cy/default.yml
src/locales/en/default.yml

The support link has been changed to the new one-login version.
Due to contact centre being onboarded to one-login.
- [LIME-834](https://govukverify.atlassian.net/browse/LIME-834)
[LIME-834]: https://govukverify.atlassian.net/browse/LIME-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-834 updating support link to one-login

---

deploy/template.yaml

Max capacity for auto scaling has been increased to 60, to match what is in core: https://github.com/govuk-one-login/ipv-core-front/blob/6199710a90ca8f68662ff0e8961dd2154294f28b/deploy/template.yaml#L457C10-L457C10
During perf test, the current capacity was hit and the system was using 100% CPU. This causes HTTP 500 errors. 
The fix recommended by perf team is to increase this limit. 
- [OJ-1742](https://govukverify.atlassian.net/browse/OJ-1742)
[OJ-1742]: https://govukverify.atlassian.net/browse/OJ-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1742: Increased max capacity for autoscaling to match IPV Core

---

deploy/template.yaml

`template.yaml` added step in and step out scaling policy.
Referenced: https://github.com/govuk-one-login/ipv-core-front/blob/main/deploy/template.yaml
Step scaling was recommended by the performance testing team as we had failed the perf testing.
- [OJ-1742](https://govukverify.atlassian.net/browse/OJ-1742)
- [IPS-162](https://govukverify.atlassian.net/browse/IPS-162)
[OJ-1742]: https://govukverify.atlassian.net/browse/OJ-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-162]: https://govukverify.atlassian.net/browse/IPS-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1742: Added step scaling policy (IPS-162)

---

deploy/template.yaml

Added IsProductionOrBuild condition to step scaling actions. This is because auto scaling was not setup for the other environments prior.

OJ-1742: Added IsProductionOrBuild condition to scaling (IPS-162)

---

.secrets.baseline
deploy/template.yaml

IPS-295 Added wildcard match to end of dynatrace resource names
IPS-295 Added wildcard match to end of dynatrace resource names
- [IPS-295](https://govukverify.atlassian.net/browse/IPS-295)
[IPS-295]: https://govukverify.atlassian.net/browse/IPS-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-295 Added wildcard match to end of dynatrace resource names

---

.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml
.gitignore

- Updated post-merge workflow to use devplatform-upload-action-ecr@1.2.0
- Updated .gitignore
- Required for canary deployments across Identity
- [IPS-493](https://govukverify.atlassian.net/browse/IPS-493)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- Image successfully pushed, with commit tag, by manually triggering workflow (to dev):
https://github.com/govuk-one-login/ipv-cri-address-front/actions/runs/7932144855/job/21657923337
[IPS-493]: https://govukverify.atlassian.net/browse/IPS-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-493: Update post-merge workflow to use devplatform-upload-action-ecr

---

src/app.js
src/views/address/address.njk
src/views/address/problem.njk
src/views/address/results.njk
src/views/address/search.njk
src/views/errors/error.njk
src/views/errors/page-not-found.njk
src/views/previous/address.njk
src/views/previous/problem.njk
src/views/previous/results.njk
src/views/previous/search.njk
src/views/summary/confirm.njk

- Revert the helmet.js import change to specific the import path within the dependency
- Update the OPL trackers to use the cspNonce
The change made to the helmet import within this CRI prevents the file from being passed through from common express. 
- [DFC-529](https://govukverify.atlassian.net/browse/DFC-529)
[DFC-529]: https://govukverify.atlassian.net/browse/DFC-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DFC-529] - Revert helmet import change and provide correct nonce for OPL Tracker

---

src/views/address/address.njk
src/views/address/results.njk
src/views/address/search.njk
src/views/components/address-input-fields.njk

This PR allows users to use the autocomplete functionality in their web browsers to complete form fields. It adds the HMPO app feature to all `hmpoForm` calls for any future additions.
There is a two-step process to add autocomplete to a form. First, the `hmpoForm` call needs autocomplete to be turned on
```
{% call hmpoForm(ctx, {autocomplete:'on'}) %}
```
then individual form fields need to have [the correct autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) added, for example:
```
{{ hmpoText(ctx, {
id: "addressLocality",
name: "addressLocality",
label: { text: translate("fields.addressLocality.label") },
classes: "govuk-input--width-20",
hint: "",
autocomplete:"address-line2"
}) }}
```
This change allows users who already have address …

CNUCD: Add autocomplete to form fields

---

package.json
yarn.lock

Updates the analytics package version to latest
The latest package release contains several bug fixes required by the analytics team to unblock their QA. The package has also been renamed to improve compliance.
This is the first major version push of the package, from this point forward dependabot should pick up new version releases.
[DFC-555](https://govukverify.atlassian.net/browse/DFC-555)
[DFC-555]: https://govukverify.atlassian.net/browse/DFC-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DFC-555: Update analytics package to v1.0.3

---

deploy/template.yaml

Enabled Welsh Toggle for Dev, Build and Stage environment for E2E testing
To run full end to end testing in the staging RP env
- [OJ-2596](https://govukverify.atlassian.net/browse/OJ-2596)
[OJ-2596]: https://govukverify.atlassian.net/browse/OJ-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2596: Enable Welsh Toggle in all env apart from Prod and Int

---

deploy/template.yaml

Increase log group's RetentionInDays to 30. Currently any log retention that is set under 30 days will be set to 30 by a Lambda attached to the LZA Lambda run - [INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
[SW-264](https://govukverify.atlassian.net/browse/SW-264)
- RetentionInDays: 14 to RetentionInDays: 30
LZA lambda unpicks log retentions lower than 30 days.
[INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
[INCIDEN-627]: https://govukverify.atlassian.net/browse/INCIDEN-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SW-264]: https://govukverify.atlassian.net/browse/SW-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

SW-264: Increase log group's RetentionInDays to 30.

---

deploy/template.yaml

Enabled waf association for cloudfront testing in dev and build
To enable the cloudfront distribution
- [IPS-739](https://govukverify.atlassian.net/browse/IPS-739)
[IPS-739]: https://govukverify.atlassian.net/browse/IPS-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add and enable WAF association for dev and build

---

deploy/template.yaml

Enabled waf association for cloudfront  in staging and integration
To enable the cloudfront distribution
- [IPS-739](https://govukverify.atlassian.net/browse/IPS-739)
[IPS-739]: https://govukverify.atlassian.net/browse/IPS-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-739 enable address waf association staging and integration

---

src/views/summary/confirm.njk

This change fixes the on page load issue on the confirmation page - all details of the bug can be found here
https://govukverify.atlassian.net/browse/DAC-3602
I have updated the On Page Load component attributes to use the correct keys, which enables the component to load on the page successfully.
The typos meant the component were not loading
https://govukverify.atlassian.net/browse/DAC-3602
Verification of the on page load tracker functioning here -

DAC-3603-bug-fix-confirmation-ga4-on-page-load-bug-fix

---

package.json
yarn.lock

Bumps the @govuk-one-login/frontend-analytics package from v1.0.3 to v2.0.0
It's been discovered that the Address select form input is sending PII as first line of address does not match regular expression patterns use to filter sensitive data and we don't prevent selects from being passed into analytics. The new package version now considers all form data sensitive which an opt-out possible for repositories that don't contain PII. 
This feature works by default, no code changes are required to enable it and first line of address was the only form response being logged from this repository so no analytics data is being lost by not opting out.
- [DAC-3600](https://govukverify.atlassian.net/browse/DAC-3600)
Note: There is a related environment variable for this work, but it is only required …

Chore: Bump frontend-analytics to v2.0.0

---

package.json
src/app.js
yarn.lock

Replace aws-sdk with @aws-sdk/client-dynamodb
aws-sdk is reaching end of life
- [OJ-2686](https://govukverify.atlassian.net/browse/OJ-2686)
[OJ-2686]: https://govukverify.atlassian.net/browse/OJ-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2686: Replace aws-sdk with @aws-sdk/client-dynamodb

---

deploy/template.yaml

Stage 1 of 2 for enabling ECS Canaries 
Added the ECSCanaryDeployment nested Stack to handle Blue/Green ECS deployments
Stage 2 can be found [here](https://github.com/govuk-one-login/ipv-cri-address-front/pull/922)
- [IPS-551](https://govukverify.atlassian.net/browse/IPS-551)
[IPS-551]: https://govukverify.atlassian.net/browse/IPS-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-551 - ECS Canary deployment for address

---

deploy/template.yaml

IPS-551 - Canary ECS deployments for Address - Rollout
This PR must not be merged until previous Canary PR is merged.
This shifts the TaskDefinition to go via the Canary Deployment but this
only occurs once the bluegreen nested stack is deployed.
Stage 2 triggering the switchover to use Canaries
- [IPS-551](https://govukverify.atlassian.net/browseIPS-551)
[IPS-551]: https://govukverify.atlassian.net/browse/IPS-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-551 - Canary ECS deployments for Address - Rollout

---

package.json
yarn.lock

common-express updated to 7.0.0
Bug fix for the `redirect_uri` being undefined
- [OJ-2724](https://govukverify.atlassian.net/browse/OJ-2724)
[OJ-2724]: https://govukverify.atlassian.net/browse/OJ-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2724: Update common-express to 7.0.0

---

test/browser/cucumber.js

Remove cucumber publish quiet
It's been deprecated as per the [docs](https://github.com/cucumber/cucumber-js/blob/main/docs/deprecations.md)

BAU: Remove cucumber publish quiet

---

deploy/template.yaml

Adds missing RetentionInDays to log group
So that they are not retained for infinity
- [OJ-2600](https://govukverify.atlassian.net/browse/OJ-2600)
[OJ-2600]: https://govukverify.atlassian.net/browse/OJ-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2600: Adds missing RetentionInDays to log group

---

src/app/address/controllers/address/prepopulate.js

Log `/addresses` endpoint failures
We intermittently see spikes in 4xx errors on this API call. I can find [API GW log](https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?q=search%20index%3D%22gds_di_production%22%20source%3D%22*address-cri-api-v1-175zgowlxb-private-AccessLogs*%22%7C%20spath%20status%20%7C%20search%20status%3D4*&earliest=%40w0&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&display.page.search.tab=events&display.general.type=events&display.events.timelineEarliestTime=1728237600&display.events.timelineLatestTime=1728241200&sid=1728292991.1047704)s but I cannot find API logs that seem to match.
Have added this log message to try and get more information about the error.

Log /addresses endpoint failures

---

src/app/address/controllers/address/manual.js
src/app/address/controllers/address/manual.test.js
test/utils/addressFactory.js

Hardcoded the value for UK addresses for `addressCountry` and updated associated unit tests 
To support international addresses because the `addressCountry` field will be made mandatory in the backend and currently its defaulted to "GB".
https://github.com/user-attachments/assets/5a2f6a1d-d9f6-46ff-a2a0-15e7cb91aef4
- [OJ-2818](https://govukverify.atlassian.net/browse/OJ-2818)
[OJ-2818]: https://govukverify.atlassian.net/browse/OJ-2818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2818: Feat - update address object to include country

---

package.json
yarn.lock

- Added yarn-audit-fix to dev dependencies to help fix vulnerabilites found by dependabot. 
- yarn-audit-fix ran
To help stay on top of vulnerabilities detected by dependabot.
To resolve  https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/45

Add and run yarn-audit-fix

---

src/app/address/controllers/address/prepopulate.js
src/app/address/controllers/address/prepopulate.test.js
src/app/address/controllers/address/search.js
src/app/address/controllers/summary/confirm.js

1. Add warn logging to errors for other API calls
2. Only make pre-population call if we have a session (part 1 of the ticket) 
We have an ongoing incident around the levels of errors being thrown by the /addresses endpoint. This PR makes sure we don't make calls that we know are going to fail, part 2 of the ticket is to stop people accessing the page incorrectly.
- [OJ-2833](https://govukverify.atlassian.net/browse/OJ-2833)
[OJ-2833]: https://govukverify.atlassian.net/browse/OJ-2833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2833: Only make pre-population call if we have a session (part 1)

---

src/app/address/controllers/summary/confirm.js
src/app/address/controllers/summary/confirm.test.js
src/app/address/routes/summary/fields.js
src/app/address/routes/summary/steps.js
src/locales/cy/fields.yml
src/locales/en/fields.yml
src/views/summary/confirm.njk
test/browser/features/address-confirm.feature
test/browser/features/address-manual-empty-previous.feature
test/browser/features/address-manual-preselected-previous.feature
test/browser/features/address-results-previous.feature
test/browser/features/address-search-previous.feature
test/browser/pages/confirm.js
test/browser/step_definitions/confirm.js

Rename isAddressMoreThanThreeMonths to hasPreviousUKAddressWithinThreeMonths to reflect change to input text.
Update hasPreviousUKAddressWithinThreeMonths text fields to specify the previous Address needs to be in the UK.
Flip the logic of the hasPreviousUKAddressWithinThreeMonths radio buttons.
- Yes now requires the user to go through adding a previous address
- No will now take you forward to the VC.
For UK users we need to collect at least 3 months worth of addresses. If a user has moved to the UK within the last 3 months, we do not need to collect another address.
- [OJ-2882](https://govukverify.atlassian.net/browse/OJ-2882)
[OJ-2882]: https://govukverify.atlassian.net/browse/OJ-2882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2882: Change within three month question to specify UK address

---

package.json
yarn.lock

Bump express-session -> 1.18.1
run yarn-aduit-fix
Resolve https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/52
- [OJ-2892](https://govukverify.atlassian.net/browse/OJ-2892)
[OJ-2892]: https://govukverify.atlassian.net/browse/OJ-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2892: BAU vuln fix

---

.github/workflows/run-unit-tests.yml
.github/workflows/scan-repo.yml

EOL on the 5th December 2024
https://govukverify.atlassian.net/browse/PSREDEV-1911
https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new
Updated a GH action
V3 being EOLed 5th Dec
https://govukverify.atlassian.net/browse/PSREDEV-1911

Update EOL GitHub provided action

---

package.json
yarn.lock

Removes yarn-audit-fix because it's not something that we actually need and it contains a vulnerability
https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/55
- [OJ-2900](https://govukverify.atlassian.net/browse/OJ-2900)
[OJ-2900]: https://govukverify.atlassian.net/browse/OJ-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2900: Removes vulnerable package

---

deploy/template.yaml

Turn off UA as it is no longer being used.
There will be subsequent tickets to deprecate but this is just to turn off as it causes a console error with new versions of the `@govuk-one-login/frontend-analytics` package.

Turn off UA as it is no longer being used

---

src/locales/en/fields.yml

- Updated `When did you start living here?` to `When did you start living at this address?` title
- Updated `Enter the year you started living at this address, for example 2017` to `Enter the year you started living here, for example 2017` hint text
Changes has been made below:
To make it consistent with the International Address screens
- [OJ-2912](https://govukverify.atlassian.net/browse/OJ-2912)
[OJ-2912]: https://govukverify.atlassian.net/browse/OJ-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2912: Fix - update content on address screen

---

src/locales/cy/fields.yml

- Updated the welsh title from `Pryd wnaethoch chi ddechrau byw yno?` to `Pryd wnaethoch ddechrau byw yn y cyfeiriad hwn?`
- Updated the welsh hint text from `Rhowch y flwyddyn y dechreuoch chi fyw yn y cyfeiriad hwn, er enghraifft 2017` to `Rhowch y flwyddyn y wnaethoch ddechrau byw yma, er enghraifft 2017` 
To make it consistent with international addresses screen
- [OJ-2912](https://govukverify.atlassian.net/browse/OJ-2912)
[OJ-2912]: https://govukverify.atlassian.net/browse/OJ-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2912: Fix - update welsh translations content on address screen

---

package.json
yarn.lock

Bump govuk-frontend to version 4.9.0
There have been changes to crown logo.
- [OJ-2914](https://govukverify.atlassian.net/browse/OJ-2914)
[OJ-2914]: https://govukverify.atlassian.net/browse/OJ-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: bump govuk-frontend to version 4.9.0

---

src/assets/scss/application.scss

Looks to be a clash with the hmpo styling on summary lists causing them not to bold the keys, which should be default when using govuk summary-list.
Disable hmpo summary list sylying by setting css variable `$hmpo-summary-list: false;` (https://github.com/HMPO/hmpo-components/blob/master/README.md?plain=1#L282)
This ensures that the styling matches the expected design and improves readability.
Note: This only covers 1 of the AC's for the ticket, the other will be in another PR.
- [OJ-2913](https://govukverify.atlassian.net/browse/OJ-2913)
[OJ-2913]: https://govukverify.atlassian.net/browse/OJ-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2913: Confirm page - make summary list keys bold

---

src/app/address/controllers/address/search.js
src/app/address/controllers/address/search.test.js
test/browser/features/address-manual-preselected-previous.feature
test/browser/features/address-manual-preselected.feature
test/browser/features/address-manual-rfc-0020-address-structure-compliance.feature
test/browser/features/address-search-previous.feature
test/browser/pages/result.js
test/data/testData.js

Basic title case implementation on addressResults from a postcode search. Added titleCaseAddresses which any addressResults from a postcode search will be passed into.
Lots of browser tests updated due to address strings no longer being caps.
To have consistent styling and addresses displayed in an easy-to-read format, so that I can clearly verify my information and have a better overall experience.
This is not a perfect solution, only a basic implementation. 
- [OJ-2913](https://govukverify.atlassian.net/browse/OJ-2913)
[OJ-2913]: https://govukverify.atlassian.net/browse/OJ-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2913: Title case address return from a post code search

---

src/app/address/controllers/address/search.js
src/app/address/controllers/address/search.test.js
src/locales/cy/default.yml
src/locales/cy/pages.yml
src/locales/en/default.yml
src/locales/en/pages.yml
src/views/previous/address.njk

Bug 1 - Change text for building address component hint from 'Fill in at least 1 field in this section' to 'Fill in at least one'
Fix 1 - Simple text change of 
```
buildingAddress:
label: Building address
hint: Fill in at least one
```
Bug - The tab on the previous address form was displaying as 'address-form-previous.title'. 
Fix 2 - Text fields were not being found, renamed/restructured them.
Bug 3 - The recent title case changed had broken the previous address comparison. The country code was also title cased and for UK address this is replaced with hardcoded in caps GB.
Fix 3 - Added addressCountry to exceptions for title casing
- [OJ-2951](https://govukverify.atlassian.net/browse/OJ-2951)
[OJ-2951]: https://govukverify.atlassian.net/browse/OJ-2951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

Oj 2951 bug fixes

---

src/app/address/controllers/address/nonUKAddress.js
src/app/address/controllers/address/nonUKAddress.test.js
src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/default.yml
src/locales/en/fields.yml

- Add welsh translations
- Removed `maxlength` where we haven't implemented `maxlength` validation
- Stopped creating our own `message` for the `buildingAddressEmptyValidator` error because the translation doesn't get updated when the language is changed
- [OJ-2883](https://govukverify.atlassian.net/browse/OJ-2883)
[OJ-2883]: https://govukverify.atlassian.net/browse/OJ-2883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2883: Add welsh translations

---

package.json
src/app.js
yarn.lock

Added overload-protection library to app.js
To prevent node from accepting too many connections and putting itself into a blocking state.
- [OJ-2864](https://govukverify.atlassian.net/browse/OJ-2864)
[OJ-2864]: https://govukverify.atlassian.net/browse/OJ-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2864: Add overload-protection

---

deploy/template.yaml

Add responseLatency to API GW log settings
To see exact frontend latency
- [OJ-2965](https://govukverify.atlassian.net/browse/OJ-2965)
[OJ-2965]: https://govukverify.atlassian.net/browse/OJ-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2965: Add responseLatency to API GW log settings

---

package.json
test/utils/mocha-helpers.js
yarn.lock

Removed `reqres` package and replaced with mocks
The package is not fit for use because it contains a number of vulnerable dependencies and is not being actively maintained
- [OJ-2920](https://govukverify.atlassian.net/browse/OJ-2920)
[OJ-2920]: https://govukverify.atlassian.net/browse/OJ-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2920: Remove stale package reqres

---

src/app.js

Increased maxEventLoopDelay
It looks like the threshold has been set too low which is causing the 503s. Core have seen spikes that aren’t being logged by the vital signs package so where they have the same average event loop delay as us they have set the max to 400 and are not seeing any issues. 
- [OJ-2992](https://govukverify.atlassian.net/browse/OJ-2992)
[OJ-2992]: https://govukverify.atlassian.net/browse/OJ-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2992: Increased maxEventLoopDelay

---

src/locales/cy/fields.yml
src/locales/en/fields.yml
test/browser/features/address-manual-preselected.feature
test/browser/features/international-address-enter-address.feature
yarn.lock

- Change non UK address form year input hint from 'Enter the year you started living at this address, for example 2017' to 'Enter the year you started living here, for example 2017' 
- Change year input field empty/required message to be 'Enter the year'
UCD requested changes.
- [OJ-2960](https://govukverify.atlassian.net/browse/OJ-2960)
[OJ-2960]: https://govukverify.atlassian.net/browse/OJ-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2960: Minor UCD address form changes

---

.pre-commit-config.yaml
deploy/template.yaml

Not updated eslint as it requires a new config format
Updated pre-commit hook to latest versions except eslint, needed for cfnlint to recognise predicitive scaling as a valid property
pre-commit hook versions
see above

Updating pre-commit hooks to latest versions

---

src/app/address/controllers/address/whatCountry.js
src/app/address/controllers/address/whatCountry.test.js
src/app/address/routes/address/steps.js
src/assets/scss/components/_country-picker.scss
test/browser/features/international-address-enter-address.feature
test/browser/step_definitions/international.js

1. The margin-bottom has been removed from the country picker:
Before: 
After:
2. When the user presses the back button, the country picker no longer keeps the previous country pre-populated in the picker. 
- [OJ-2959](https://govukverify.atlassian.net/browse/OJ-2959)
[OJ-2959]: https://govukverify.atlassian.net/browse/OJ-2959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2959: tweaks to /what-country page

---

deploy/template.yaml

This is in ForecastOnly mode to gather data on how it behaves, I've added the scaling policy to all environments instead of just build and prod to simplify the cloudformation and align environments.
This adds a new Predicitive scaling policy which will scale the number of instances based on some AWS created  algorithm using the previous traffic patterns as input. See this for more information:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-predictive-scaling.html
Added capacity mapping for ECS task counts and removed condition on creating auto scaling policy, also added policy as above.
We want to save money, be environmentally friendly, and serve our users reliably. 
https://govukverify.atlassian.net/browse/IPS-1284

Added Predictive scaling policy

---

src/app/address/controllers/address/manual.js
src/app/address/controllers/address/manual.test.js
src/views/address/address.njk
src/views/previous/address.njk

Refactored addressFormTitle logic to be in the controller rather than a conditional in the nunjucks file. 
- [OJ-2951](https://govukverify.atlassian.net/browse/OJ-2951)
[OJ-2951]: https://govukverify.atlassian.net/browse/OJ-2951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2951: Refactor addressFormTitle to move conditional out of template

---

.github/workflows/code-quality.yml
package.json
src/app.js
yarn.lock

- Upgrade to common express version 10
- Upgrades pre-commit GHA to run with node 20
To get latest fixes from common express
- [OJ-2927](https://govukverify.atlassian.net/browse/OJ-2927)
[OJ-2927]: https://govukverify.atlassian.net/browse/OJ-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2927: Upgrade to common express version 10

---

src/app/address/controllers/address/nonUKAddress.js
src/app/address/controllers/address/whatCountry.js
src/app/address/controllers/address/whatCountry.test.js

WhatCountryController has been changed to return the error with callback if its present. 
Looking at other uses of `async getValues` most cases use `callback(null, values)` or only set the err parameter when there is actually an error. 
Example when used when there is an error: https://github.com/govuk-one-login/ipv-cri-address-front/blob/10f17d519c2b90bf39154b6b948e2e6807394b4f/src/app/address/controllers/address/nonUKAddress.js#L39
Example using null: https://github.com/govuk-one-login/ipv-cri-address-front/blob/10f17d519c2b90bf39154b6b948e2e6807394b4f/src/app/address/controllers/address/manual.js#L55

feat: return err when there is an error set

---

deploy/template.yaml

Scale Out
- Reduce cooldown from 120 seconds to 60
- Add Step adjustment for 60% - 80% to scale 100%
Scale In
- Reduce cooldown from 420 seconds to 300
- Add adjustment for 40% - 20% of 10%
Implement a new ECS scaling policy is more robust than the existing based on information in the linked ticket. 
- [OJ-2734](https://govukverify.atlassian.net/browse/OJ-2734)
Tested using perf tests to trigger scaling and validate it still works, a full perf test will be needed to see if it improves performance.
Note: Max 4, Min 1 tasks in Dev
[OJ-2734]: https://govukverify.atlassian.net/browse/OJ-2734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2734: Adjust scaling policy

---

Dockerfile
deploy/template.yaml
dev.Dockerfile
local.Dockerfile

**Before:** _No HealthCheck command configured_
**After** _HealthCheck command configured_
Currently load balancers are configured to call healthcheck endpoints to ensure that the target is healthy and ready to receive traffic, but also we need to implement configuration to for the task definition.
So as to enable it replace unhealthy tasks before the point of them being requested by the load balancer.
NB: 
The ECS TaskDefinition health is the primary mechanism ECS will use to monitor
ECS container health check, the healthcheck in the docker are mainly for consistency and local environment.
see note: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-healthcheck.html
- [OJ-2870](https://govukverify.atlassian.net/browse/OJ-2870)
[OJ-2870]: …

OJ-2870 configure ecs healthcheck

---

Dockerfile
dev.Dockerfile

In https://github.com/govuk-one-login/ipv-cri-address-front/pull/1061 
command to include curl was missing, and this caused the healthcheck to fail
Added and updated Dockerfile with missing curl
command
This is corrective change
- [OJ-2870](https://govukverify.atlassian.net/browse/OJ-2870)
[OJ-2870]: https://govukverify.atlassian.net/browse/OJ-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2870: Update docker file

---

Dockerfile
package.json

- Add licence to package.json
- Join RUN commands
- Don't set yarn version as it's determined by the .yarnrc.yml file
- Use an ARG for the base image SHA
---
- Run yarn install
Check in the lock file

OJ-2870: Address dockerfile warnings and linting errors

---

deploy/template.yaml

Revert staging log level back to warn
We are finished debugging
- [PYIC-7942](https://govukverify.atlassian.net/browse/PYIC-7942)
[PYIC-7942]: https://govukverify.atlassian.net/browse/PYIC-7942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7942: Revert staging log level back to warn

---

src/views/address/enter-non-UK-address.njk
src/views/components/address-year-from-field.njk
src/views/components/building-address/template.njk

1. Add label text next to visually hidden class
Previous:
Current:
2. Updated the `When did you start living at this address?` to H2 and new class
Previous:
Current:
3. Add extra HMTL semantic markup and added aria-describedby to hint label
Previous: 
Current:
Based on accessibility fixes found during audit
- [OJ-2998](https://govukverify.atlassian.net/browse/OJ-2998)
[OJ-2998]: https://govukverify.atlassian.net/browse/OJ-2998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2998: Fix - add label next to visually hidden label

---

src/views/components/building-address/template.njk

Add `role="list"` to the `<ol>` tag to fix Safari voiceOver
Based on the known issue [here](https://govtnz.github.io/web-a11y-guidance/wct/lists/make-a-list-accessible.html#other-accessibility-considerations) from Derren's retest Safari did not announce the listed items 
Chrome worked as expected.
- [OJ-2998](https://govukverify.atlassian.net/browse/OJ-2998)
[OJ-2998]: https://govukverify.atlassian.net/browse/OJ-2998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2998: Fix - add role to fix Safari voiceOver

---

src/views/components/address-year-from-field.njk
src/views/components/building-address/non-UK-building-address-input.njk
src/views/components/non-UK-address-input-fields.njk

hmpoForm has autocomplete hardcoded to off. Instead of creating our own form component, add autocomplete individually to the remaining inputs without autocomplete already set.
This has only be applied to the enter-non-UK-address form and both address form year inputs (shared component)
See hmpoForm here: https://github.com/HMPO/hmpo-components/blob/f1036ee824dff7fec95277e338e2a5fb7489b4ae/components/hmpo-form/macro.njk#L8
Evidence linked PR in the ticket (UK Address) does not actually work and has `autocomplete: off`
Ensure that autocomplete works across the international address form, allowing users to fill in details faster if saved information is available.
- [OJ-2999](https://govukverify.atlassian.net/browse/OJ-2999)
[OJ-2999]: …

OJ-2999: Add autocomplete on to all int address form fields

---

sonar-project.properties
src/app/address/routes/sharedFields.js
src/app/address/validators/underMaxLengthValidator.js
src/app/address/validators/underMaxLengthValidator.test.js
src/locales/cy/fields.yml
src/locales/en/fields.yml
test/browser/features/international-address-enter-address.feature

Currently on the international address form, maxLength is set as a HTML property and stops users inputting char's over that length.
This PR adds our own validator 'underMaxLength', that will just do validation on the field and not add the maxlength HTML property to it.
Fix: `sonar-project.properties` was missing a comma so the `sharedFields.js` was being included in test coverage which was failing on this PR.
To ensure that the international address form adheres to accessibility standards.
- [OJ-2999](https://govukverify.atlassian.net/browse/OJ-2999)
[OJ-2999]: https://govukverify.atlassian.net/browse/OJ-2999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2999: Change max length to validation only

---

deploy/template.yaml

Increased cpu of the ECS container to 2048 units, also increased memory to 4096 to be compatible.
The main eventLoop is slowing under load, more CPUs allow async processes to execute in a second cpu off the main thread.

DCP-4451 Increase vCPU to 2, to help speed up main eventLoop

---

src/views/address/address.njk
src/views/address/results.njk
src/views/address/search.njk
src/views/components/address-confirm.njk
src/views/components/address-problem-field.njk
src/views/previous/address.njk
src/views/previous/results.njk
src/views/previous/search.njk

`data-nav` and `data-link` have been added to `hmpoSubmit` components for analytics navigation tracking 
Without these data attributes, the navigation tracker will not fire
- [DFC-717](https://govukverify.atlassian.net/browse/DFC-717)
[DFC-717]: https://govukverify.atlassian.net/browse/DFC-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dfc-717): add data attributes for navigation tracking

---

src/app.js

- Added `proccess.exit(0)` method to prevent SIGTERM being called twice
- Due to SIGTERM erroring when trying to close the server the second time
- [OJ-2871](https://govukverify.atlassian.net/browse/OJ-2871)
[OJ-2871]: https://govukverify.atlassian.net/browse/OJ-2871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2871: Fix - prevent SIGTERM being called twice

---

src/app.js
src/middleware/missingRedirectErrorHandler.js
src/middleware/missingRedirectErrorHandler.test.js
test/utils/mocha-helpers.js

Add middleware to handle `Missing redirect_uri` error. It will now Log the error as a warn, return a 400 and pass the user to the error page.
In the future we should lookup at how uses route through our app without oauth, and how we handle Axios errors.
This error is causing a lot of noise in the logs making it difficult to debug other problems, and causing 500 errors for users which impacts our availability metrics.
- [OJ-2794](https://govukverify.atlassian.net/browse/OJ-2794)
[OJ-2794]: https://govukverify.atlassian.net/browse/OJ-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2794: Add missing redirect error handling middleware

---

src/app/address/controllers/address/manual.js

Only sends `validFrom` in the body to `/address` if the value is not null (is truthy)
I've turned on body validation on the `/address` endpoint to for https://github.com/govuk-one-login/ipv-cri-address-api/pull/1236 but the validation is failing when previous address are present with the `validFrom` null.

Fix: Address with previous is sending validFrom with null value

---

src/app/address/data/countries.json

Fix translation keys for missing countries
Copy and paste error meant that the keys for Cyprus and Panama were showing at Cuba and Palau
Before
After
- [OJ-3167](https://govukverify.atlassian.net/browse/OJ-3167)
[OJ-3167]: https://govukverify.atlassian.net/browse/OJ-3167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3167: Fix keys for missing countries

---

package.json
src/app.js
src/lib/config.js
yarn.lock

Removed existing overload-protection, replaced with common-express implementation.
Remove custom logic. 
- [OJ-3121](https://govukverify.atlassian.net/browse/OJ-3121)
[OJ-3121]: https://govukverify.atlassian.net/browse/OJ-3121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3121: Use common-express overload-protection

---

deploy/template.yaml

Add slack alerts to all alarms.
So that we have visibility of our Alarms changing state, we want to ensure all of our alarms are configured to post to our Slack channels when they change state. 
This can help us catch issues faster if there are issues with new changes.
- [OJ-3188](https://govukverify.atlassian.net/browse/OJ-3188)
[OJ-3188]: https://govukverify.atlassian.net/browse/OJ-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3188: Add slack alerts to all alarms

---

deploy/template.yaml

- Change SupportManualURL to mapping
- Add SupportManualURL to alarms where it wasn't present
Because params can't be easily updated
Before
After
- [OJ-3214](https://govukverify.atlassian.net/browse/OJ-3214)
[OJ-3214]: https://govukverify.atlassian.net/browse/OJ-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3214: Change SupportManualURL to mapping

---

.github/workflows/code-quality.yml
.github/workflows/run-browser-tests.yml
.github/workflows/run-unit-tests.yml
.github/workflows/scan-repo.yml

Upgrade github-actions to latest version
We are seeing a message saying we're using out of date actions, this was upgraded in the github-actions library [here](https://github.com/govuk-one-login/github-actions/blob/c8eefadf581d2087ce2af48b7060c1329cfa5251/code-quality/codeql/action.yml#L35)

BAU: Upgrade github-actions to latest version

---

package.json
test/browser/pages/relying-party.js
test/mocks/mappings/addresses.json
test/mocks/mappings/authorization-error.json
test/mocks/mappings/international-addresses.json
test/mocks/mappings/pre-populated-postcode.json
test/mocks/mappings/prepopulated-addresses.json
test/mocks/mappings/relying-party.json
yarn.lock

- Bump @govuk-one-login/frontend-ui resolved version
- Bump govuk-frontend as it's a peer dependency
- Change from using example.com to a wiremock endpoint for mocking relying party because there seems to be issues getting responses from example.com
Font size was 14px but needs to be 16px
- [OJ-3308](https://govukverify.atlassian.net/browse/OJ-3308)
[OJ-3308]: https://govukverify.atlassian.net/browse/OJ-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3308: Bump @govuk-one-login/frontend-ui version

---

package.json
yarn.lock

Updated `frontend-ui` package and when running yarn install updates a few dependencies too
Before using the stubs:
https://github.com/user-attachments/assets/b73f580c-0ad2-4efb-8700-3d66a97efb6c
After with the fix:
https://github.com/user-attachments/assets/56638a18-1b05-47ef-a119-cc13426322d5
To enable branding.
- [OJ-3322](https://govukverify.atlassian.net/browse/OJ-3322)
[OJ-3322]: https://govukverify.atlassian.net/browse/OJ-3322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3322: chore - bump frontend package to use latest changes for FEC

---

package.json
yarn.lock

Fix dependabot vulnerability by updating the parent dependency `express-session` then which lead to updating the 'on-headers` dependency from 1.0.2 to 1.1.0
To resolve dependabot issue
- [OJ-3318](https://govukverify.atlassian.net/browse/OJ-3318)
[OJ-3318]: https://govukverify.atlassian.net/browse/OJ-3318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3318: chore - vulnerability fix

---

package.json
yarn.lock

Fix dependabot vulnerability by updating @cucumber/cucumber version which doesn't seem to depend on tmp
Vulnerability highlighted as a result of
```
Transitive dependency tmp 0.2.3 is introduced via
@cucumber/cucumber 9.5.1  tmp 0.2.3
```
see: https://github.com/orgs/govuk-one-login/security/alerts/dependabot?q=is:open%20props.pod:Identity%20team:cri-orange-team
https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/85
- [OJ-3330](https://govukverify.atlassian.net/browse/OJ-3330)
[OJ-3330]: https://govukverify.atlassian.net/browse/OJ-3330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3330: vulnerability fix

---

deploy/template.yaml

use stack name in AddressFrontSessionsTable name for dev environment.
so that we can create multiple FE stacks without the table name conflicting as it will already exist for the main stack.
* New session table created and the old one has been deleted in dev
* FE still works via core stub
- [OJ-3424](https://govukverify.atlassian.net/browse/OJ-3424)
[OJ-3424]: https://govukverify.atlassian.net/browse/OJ-3424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

use stack name in AddressFrontSessionsTable name

---

package.json
yarn.lock

see https://github.com/govuk-one-login/ipv-cri-address-front/pull/1229
Upgraded **wait-on** see https://github.com/jeffbski/wait-on/releases/tag/v8.0.5
to version without vulnerability
https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/89
- [OJ-3346:](https://govukverify.atlassian.net/browse/OJ-3346:)

OJ-3346: Vulnerability fix for axios

---

deploy/template.yaml

- Enabled drop_invalid_header_fields on frontend ALB
- This setting checks that header names conform to `[-A-Za-z0-9]+` and drops any that do not. This is beneficial as it will protect the frontend application from potentially unsafe header keys.
- [OJ-3356](https://govukverify.atlassian.net/browse/OJ-3356)
[OJ-3356]: https://govukverify.atlassian.net/browse/OJ-3356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3356: Enable drop_invalid_header_fields on ALB

---

Dockerfile
dev.Dockerfile

- Change `node app.js` to `node src/app.js` to correctly imitate the `start` script in package.json
`app.js` is not in the root of the repository.
- [OJ-3337](https://govukverify.atlassian.net/browse/OJ-3337)
[OJ-3337]: https://govukverify.atlassian.net/browse/OJ-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3337: Resolve typo in file path

---

deploy/template.yaml

As part of transitioning FMS WAF rule enforcement from COUNT to BLOCK, Security have set up custom policies for us to apply to our resources in scope. In COUNT mode FMS merely logs the rule violations, in BLOCK mode violating requests are actively blocked. 
The tags to implement this should only apply (conditionally) to resources deployed to dev, build and staging accounts. The tags must not apply to int and prod (there is a follow-up ticket for this:
Apply tagging conditional to meet the above requirement
**Tags On Load Balancer**
**Tags On ApiGateway**
Part of transitioning FMS WAF rule enforcement
- [OJ-3444](https://govukverify.atlassian.net/browse/OJ-3444)
[OJ-3444]: https://govukverify.atlassian.net/browse/OJ-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

OJ-3444: Added custom policy for inclusion in custom-managed policy
