govuk-one-login/ipv-cri-address-front

src/app/address/controllers/address.js
src/app/address/controllers/addressResults.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/locales/en/default.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/address/address.html

Updating the content to match the approved content provided.
- [KBV-189](https://govukverify.atlassian.net/browse/KBV-189)

KBV-189-add-successful-path-content

---

.eslintrc.js
src/app.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/controllers/addressResults.test.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/lib/axios.js
test/application/features/address.feature
test/mocks/mappings/addresses.json
test/utils/mocha-helpers.js

Add the scenario headers into axios. 
This change will allow testing of specific scenarios using wiremock and scenario headers to control the api output.

Kbv 181 add scenario headers

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/controllers/addressResults.test.js
src/app/address/controllers/addressSearch.js
src/app/address/controllers/addressSearch.test.js
test/data/testData.js
test/mocks/mappings/addresses.json
test/utils/addressFactory.js

Rename model thoroughfareName to StreetName to match model changes.
The [address RFC](https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0020-address-structure.md) has resulted in a small change the address model. This change needs to be reflected on both frontend and backend.
- [KBV-338](https://govukverify.atlassian.net/browse/KBV-338)

KBV-338-update-frontend-address-model-to-match-RFC

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/address/address.html

Refactor: align UI with the designs
As per the design update, this PR will reflect those changes on the manual address entry page.
- [KBV-364](https://govukverify.atlassian.net/browse/KBV-364)
- [Parent KBV-359](https://govukverify.atlassian.net/browse/KBV-359)
Edit - missing browser test updates for now.
note: The logo in the input fields is from a local extension

KBV-364-update-manual-address-pages

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/views/address/confirm.html
test/utils/addressFactory.js

Add the year from value to the confirm details page.
as part of the journey the user will confirm their details, the year value should appear here.
- [KBV-375](https://govukverify.atlassian.net/browse/KBV-375)

KBV-375 show year value in check your details

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/locales/en/fields.yml
src/views/address/confirm.html

View of a radio modal that displays the question of if the user has lived there for more than 3 months under specific conditions. 
As part of Address journey we want to be able to gather additional addresses if the users have lived at the address for less than 3 months.
- [KBV-373](https://govukverify.atlassian.net/browse/KBV-373)

KBV-373 show have you lived here message if year value is less than 3 months

---

src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/fields.js
src/app/address/steps.js
src/locales/en/fields.yml
src/views/address/address.html
src/views/address/confirm.html
src/views/address/previous.html

When the user enters the previous address journey, they should be directed to whats your previous address screen.
To gather previous addresses when their current address is not enought.
- [KBV-392](https://govukverify.atlassian.net/browse/KBV-392)

Kbv 392 change user journey when less than 3 months

---

.prettierignore
package.json
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressSearch.js
src/locales/en/default.yml
src/locales/en/pages.errors.yml
src/locales/en/pages.yml
test/browser/README.md
test/browser/compose.yml
test/browser/cucumber.js
test/mocks/mappings/addresses.json

Prettier should be run in IDEs and as part of linting to avoid code formatting wars.

chore: Run prettier in lint script

---

wallaby.conf.js

Add `test/data` to wallabyjs config

fix: Add test data to wallabyjs config

---

src/app.js
src/lib/redis.js
src/lib/redis.test.js

Refactor `redis` to pass in config, rather than retrieve it itself. This will make it easier to extract out for reuse.

refactor: Pass config into redis lib to remove dependency

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

Restructured the tests, added some tests for saving `session_id` and some error handling.
- [KBV-397](https://govukverify.atlassian.net/browse/KBV-397)

Refactor initSession middleware

---

src/app/address/validators/addressValidator.js
src/app/address/validators/addressValidator.test.js
src/locales/en/fields.yml
src/locales/en/pages.yml

Update content for page titles and a small validation change.
This PR aligns the product with the content.

Content revisions

---

Dockerfile

Add Dockerfile to build a container image of the frontend code
Image is required for migration to Fargate
- [KBV-421](https://govukverify.atlassian.net/browse/KBV-421)

KBV-421: add Dockerfile

---

deploy/template.yaml

Deploy frontend to Fargate
Create Fargate deploy template
Migration from PaaS to Fargate
- [KBV-417](https://govukverify.atlassian.net/browse/KBV-417)

KBV-417: Add fargate deploy template

---

src/app/address/fields.js
src/app/address/steps.js
src/locales/en/default.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/address/components/address-problem-field.html
src/views/address/previous/problem.html
src/views/address/problem.html

Add address problem view, which happens when an error occurs from OS API.
- [KBV-374](https://govukverify.atlassian.net/browse/KBV-374)

KBV-374-add-there-is-a-problem-page

---

src/app/address/controllers/address.js
src/app/address/validators/addressValidator.js
src/app/address/validators/addressValidator.test.js

Added validation to house name or number requirement.
We need validation on both house name or number to say that at least one of the values have been populated.
- [KBV-371](https://govukverify.atlassian.net/browse/KBV-371)

KBV-371-Add validation for house name and number fields

---

src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/address/confirm.html

Caught up with Tom regarding content on address pages. A few minor changes needed in this PR.

BAU-content-correction-for-changes

---

README.md
package.json
src/locales/en/default.yml
src/views/address/confirm.html
test/browser/features/address-confirm.feature
test/browser/features/address-manual-empty.feature
test/browser/features/address-manual-preselected.feature
test/browser/features/address-search.feature
test/browser/pages/address.js
test/browser/pages/confirm.js
test/browser/pages/ipv-core.js
test/browser/pages/result.js
test/browser/step_definitions/IPVCore.js
test/browser/step_definitions/RelyingParty.js
test/browser/step_definitions/address.js
test/browser/step_definitions/confirm.js
test/browser/step_definitions/error.js
test/browser/step_definitions/problem.js
test/browser/step_definitions/results.js
test/browser/step_definitions/search.js

Adds manual address browser tests
Refactored the browser tests to have a file of steps per page.
and behaviours matched up to the pages they're primarily associated with. 
For example, if we're testing the behaviour of the confirmation page edit buttons, we would want to test more than just the confirmation page, we want to test a predicted journey of going back and changing address details. 

Bau update browser manual address tests

---

src/locales/en/default.yml
test/browser/features/address-confirm.feature
test/browser/features/address-search-previous.feature
test/browser/pages/address.js
test/browser/pages/problem.js
test/browser/pages/result.js
test/browser/pages/search.js
test/browser/step_definitions/confirm.js
test/browser/step_definitions/search.js
test/mocks/mappings/addresses.json

Browser tests: add browser tests for previous address search journey
- same tests as current address but testing previous address route.

BAU- add browser tests for previous address search

---

src/app/address/controllers/address.js
src/app/address/controllers/address.test.js
src/app/address/controllers/addressConfirm.js
src/app/address/controllers/addressConfirm.test.js
src/app/address/controllers/addressResults.js
src/app/address/controllers/addressResults.test.js
src/app/address/routes/previous/steps.js
src/app/address/validators/confirmationValidator.js
test/utils/mocha-helpers.js

BAU Refactor to use the new wizard

---

package.json
src/app.js
yarn.lock

Add `express-async-errors` to catch async errors as a part of the default Express events.
Without this module, async errors crash the server.

chore: Add express-async-errors to handle unchaught errors

---

src/views/previous/address.html
src/views/previous/results.html

bugfix: change title from current to previous
- [KBV-571](https://govukverify.atlassian.net/browse/KBV-571)

KBV-571-previous-address-journey-title-change-from-current-to-previous

---

package.json
src/locales/en/default.yml
src/locales/en/pages.yml
src/views/errors/error.html
test/browser/pages/error.js
yarn.lock

#Dont merge yet. 
Added a technical error page that links back to gov.uk. The page is held in common folder for reuse across all CRIs.
- [KBV-390](https://govukverify.atlassian.net/browse/KBV-390)

KBV-390-technical-error

---

package.json
yarn.lock

Common version update
Update common

Common update

---

deploy/template.yaml

Update gateway id.
Update gateway.

BAU-update-gateway-id

---

deploy/template.yaml

Chore: change health check to match hmpo healthcheck

BAU-change-health-check

---

src/locales/en/default.yml
src/locales/en/fields.yml

Remove full stops from error messages
Add capital letters to change links
Corrections to content

Content: minor accessibility corrections

---

deploy/template.yaml

Add SubscriptionFilter to ECS logs.
This pattern has worked on the KBV frontend.
- [KBV-618](https://govukverify.atlassian.net/browse/KBV-618)

KBV-618 Add SubscriptionFilter to ECS logs

---

src/views/address/address.html
src/views/address/results.html
src/views/address/search.html
src/views/components/address-problem-field.html
src/views/previous/address.html
src/views/previous/results.html
src/views/previous/search.html
src/views/summary/confirm.html

Add govuk-heading-l style to <h1>
- [KBV-686](https://govukverify.atlassian.net/browse/KBV-686)

Add govuk-heading-l style to <h1>

---

src/locales/en/default.yml

Add `govuk-link` to `<a>` tags so that can be more accurately tracked.
- [KBV-686](https://govukverify.atlassian.net/browse/KBV-686)

fix: Use govuk-link style on <a> tags

---

src/locales/en/default.yml

Update link to the cookie policy
- [KBV-670](https://govukverify.atlassian.net/browse/KBV-670)
- https://github.com/alphagov/di-ipv-cri-common-express/pull/72 - this needs to be merged and released as well

feat: Change link to account.gov.uk cookie policy

---

deploy/template.yaml

Output the stack name from the API template, so that it can be used in the acceptance test CodeBuild script.
- [KBV-672](https://govukverify.atlassian.net/browse/KBV-672)

BAU Output the stack name

---

.github/workflows/post-merge-to-build.yml

Update secrets to include environment in name
To distinguish between the secrets
- [OJ-822](https://govukverify.atlassian.net/browse/OJ-822)

OJ-822 update front gh secrets

---

.github/pull_request_template.md

BAU-update-pr-template

---

deploy/template.yaml

OJ-878-Double-desired-count-memory-and-CPU

---

package.json
src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/cy/pages.yml
test/browser/features/translation.feature
test/browser/step_definitions/background.js
test/browser/step_definitions/search.js

Browser test to test that with the cookie change and a reload - the content is translated from English to Welsh. The tests are set to skip for now.
Small content change to check that the search page is translated when the cookie is set to welsh. The content is not finalised and is just a google translate for now. The real content will be replacing the current content.
- [OJ-865](https://govukverify.atlassian.net/browse/OJ-865)

Oj 865 create browser tests for translations

---

deploy/template.yaml

Revert autoscaling change

---

deploy/template.yaml

Set scaling to 2 and 4

---

src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/cy/pages.errors.yml
src/locales/cy/pages.yml

Add Welsh content
- [OJ-864](https://govukverify.atlassian.net/browse/OJ-864)

Add Welsh content

---

test/browser/features/translation.feature
test/browser/step_definitions/background.js
test/browser/step_definitions/search.js

Add Welsh translation content
Depends on PR - https://github.com/alphagov/di-ipv-cri-address-front/pull/330 going first. 
Added welsh translations to the content.
- [OJ-882](https://govukverify.atlassian.net/browse/OJ-882)

OJ-882-see-address-cri-in-welsh

---

.github/workflows/checks.yml
.husky/pre-commit
package.json
yarn.lock

Updated common express and added check translation script.
Add check translation script.
As part of the Welsh translation it would be good to have a check for the keys in place.

OJ-863-check-translations

---

.husky/pre-commit
.secrets.baseline
package.json
yarn.lock

Add pre commit hook to check for security leaks.
- [OJ-926](https://govukverify.atlassian.net/browse/OJ-926)

Oj 926 add security Pre-commit hook

---

.github/workflows/checks.yml
.github/workflows/i18n.yml

i18n checks are set to run separately to the main build checks.
This allows them to be set as required or advisory without requiring pipeline changes.

chore: Run i18n checks in separate workflow

---

src/app.js

Investigation of user IP addresses as deployed in AWS

Feat: Add debug route to investigate user IP headers

---

src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/en/default.yml

- [OJ-913](https://govukverify.atlassian.net/browse/OJ-913)

Fix translations after content review

---

src/app.js

Add debug route for testing

---

src/app.js

remove debug route

---

deploy/template.yaml

- Changed the ImportValue function syntax
- Fix the unsupported function error
- [OJ-968](https://govukverify.atlassian.net/browse/OJ-968)

OJ-968 - correct the ImportValue function usage 

---

deploy/template.yaml

- ImportValue has been moved to it's own line
- To correct a SAM validation error
- [OJ-968](https://govukverify.atlassian.net/browse/OJ-968)

OJ-968 - fix sam validation error

---

src/locales/cy/default.yml
src/locales/en/default.yml

Add `houseNameOrHouseNumber` into locales files for English and Welsh.

Add localisation for error message

---

src/locales/cy/default.yml
src/locales/en/default.yml

Add missing `addressSelect` to locales

Add addressSelect to locales for en and cy

---

src/locales/cy/default.yml
src/locales/en/default.yml

Update the locales files
- [OJ-981](https://govukverify.atlassian.net/browse/OJ-981)

chore: Update locales files

---

.gitignore

tiny chore to gitignore intellij *.iml files

chore: ignore intellij *.iml files

---

src/app/address/controllers/summary/confirm.test.js
src/presenters/addressPresenter.js
src/presenters/addressesToSelectItems.test.js
test/browser/features/address-manual-rfc-0020-address-structure-compliance.feature
test/utils/addressFactory.js

Display building number alongside building name on confirm address page.
Go from this confirm address layout
````
FLAT 7 115
BAROSSA WAY
.....
````
To this:
````
FLAT 7
115 BAROSSA WAY
.....
````
- [OJ-1013](https://govukverify.atlassian.net/browse/OJ-1013)

OJ-1013 Display building number alongside building name on confirm address page

---

.github/dependabot.yml

add dependabot config for GHA
Makes it easier to track updates to our pipeline including any major security updates that must happen.

OJ-1050-Add-dependabot-update-for-gha

---

.prettierignore

Add `.yarn` folder to `.prettierignore` so that the folder isn't processed during `pre-commit run --all`

Add .yarn folder to prettierignore

---

.github/workflows/checks.yml
.github/workflows/codeql.yml
.github/workflows/i18n.yml
.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml

Workflows have been updated:
* Deprecated GHA actions have been updated to the newer versions.
* setup-sam fix has been applied
Primarily to apply the setup-sam fix so that the workflows are not broken.
(https://github.com/aws/aws-sam-cli/issues/4527)
Secondly in preparation for GitHub to remove the deprecated functionality.
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1146 workflow deprecations and sam fix

---

.github/workflows/checks.yml
test/browser/cucumber.js

- [OJ-1449](https://govukverify.atlassian.net/browse/OJ-1449)
[OJ-1449]: https://govukverify.atlassian.net/browse/OJ-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added code for cucumber reporting

---

.github/workflows/checks.yml

added a line of code to see if the bug with deploying gh-pages is now covered

Added an if statement to only push ghp if a person commits

---

test/browser/features/address-confirm.feature
test/browser/features/address-manual-empty-previous.feature
test/browser/features/address-manual-empty.feature
test/browser/features/address-manual-preselected-previous.feature
test/browser/features/address-manual-preselected.feature
test/browser/features/address-manual-rfc-0020-address-structure-compliance.feature
test/browser/features/address-results-previous.feature
test/browser/features/address-search-previous.feature
test/browser/features/back-button-post-session.feature
test/browser/features/error-authorization.feature
test/browser/features/flat-number.feature
test/browser/pages/address.js
test/browser/pages/confirm.js
test/browser/step_definitions/address.js
test/browser/step_definitions/confirm.js

Date Drift issue fix
Code to automatically decide the year to be entered

Date Drift Refactoring

---

deploy/template.yaml

template.yaml
In order to do effective performances tests that accurately reflect how high volume would effect production - we need our testing environment to match that of production.
- [OJ-1631](https://govukverify.atlassian.net/browse/OJ-1631)
[OJ-1631]: https://govukverify.atlassian.net/browse/OJ-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1631: Updated template.yaml

---

package.json
yarn.lock

Update to common-express 3.2.0

chore: Update common-express@3.2.0

---

deploy/template.yaml
src/app.js
src/lib/config.js

- Add support for overriding log level
- Add config for log level differences between dev/build and staging/production/integration

Add log level

---

deploy/template.yaml

CPU and memory increased. 
During performance tests, the system was at 100% CPU causing HTTP 500 errors to occur. 
- [OJ-1742](https://govukverify.atlassian.net/browse/OJ-1742)
[OJ-1742]: https://govukverify.atlassian.net/browse/OJ-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1742: Increased CPU to 1024 and memory to 2048

---

CODEOWNERS

Update Codeowners with govuk-one-login teams

chore: Update Codeowners with govuk-one-login teams

---

.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml
.pre-commit-config.yaml
.secrets.baseline
Dockerfile
deploy/template.yaml

IPS-295 Added Dynatrace layer
Updated pre-commit added checkov hook and cfn-lint (to catch cloudformation issues)
updated all necessary files to integrate dynatrace.
IPS-295 Added Dynatrace layer
Updated pre-commit added checkov hook and cfn-lint (to catch cloudformation issues)
updated all necessary files to integrate dynatrace.
- [IPS-295](https://govukverify.atlassian.net/browse/IPS-295)
[IPS-295]: https://govukverify.atlassian.net/browse/IPS-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-295 Added Dynatrace layer

---

CODEOWNERS

BAU updated codeowners
BAU updated codeowners

BAU updated codeowners

---

.nycrc.yml
sonar-project.properties

Ignore form-wizard config in sonar.properties

test: Add config filepaths to sonar.exclusions

---

src/locales/cy/fields.yml
src/locales/en/fields.yml

fix: Add empty locales for radio hint/reveal

---

package.json
yarn.lock

- update govukfrontend-4.8
- update ipv-cri-common-express 5.1
- [OJ-2284](https://govukverify.atlassian.net/browse/OJ-2284)
[OJ-2284]: https://govukverify.atlassian.net/browse/OJ-2284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Use tudor crown

---

src/locales/cy/default.yml
src/locales/en/default.yml

**This is a draft request to check the Accessibility team has access**
Update the footer content to have consistent wording and behaviour
Two yaml files were updated.
These changes ensure users have the same experience throughout the journey. They mean the CRI will meet [WCAG 2.2 3.2.6 Consistent Help](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help)
- [CNUCD-261](https://govukverify.atlassian.net/browse/CNUCD-261)
[CNUCD-261]: https://govukverify.atlassian.net/browse/CNUCD-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update footer link behaviour to match journey

---

package.json
src/app.js
src/assets/scss/application.scss
yarn.lock

Update language toggle dependency, and use new nujucks global
- [OJ-2562](https://govukverify.atlassian.net/browse/OJ-2562)
[OJ-2562]: https://govukverify.atlassian.net/browse/OJ-2562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Use updated language toggle and cri-common-express

---

deploy/template.yaml

Deployments into staging were failing with an error of:
```
22 May 2024 at 15:31 (UTC+1:00)	throw Error(`default level:${defaultLevel} must be included in custom levels`)	app
22 May 2024 at 15:31 (UTC+1:00)	^	app
22 May 2024 at 15:31 (UTC+1:00)	Error: default level:request must be included in custom levels	app
22 May 2024 at 15:31 (UTC+1:00)	at assertDefaultLevelFound (/app/node_modules/pino/lib/levels.js:194:11)	app
```
This is due to Pino inside the @govuk-one-login/frontend-passthrough-headers module  
[being configured without custom levels](https://github.com/govuk-one-login/frontend-passthrough-headers/blob/main/src/utils/logger.ts#L5C62-L5C66). This causes a runtime error on deplyment when the `LOG_LEVEL` is set to an unexpected value.
As a quick fix, the LOG_LEVEL can be slightly …

Update default LOG_LEVEL to warn for staging and higher environments

---

package.json
yarn.lock

[OJ-2571] Accessibility Fix - Focus on Error Summary
updated di-ipv-cri-common-express to include the fix
[OJ-2571](https://govukverify.atlassian.net/browse/OJ-2571)
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updated common express version to include the fix.

---

deploy/template.yaml

Set ga4Disabled to false for integration and prod.
Enable GA4 Toggle in Production
- [OJ-2648](https://govukverify.atlassian.net/browse/OJ-2648)
[OJ-2648]: https://govukverify.atlassian.net/browse/OJ-2648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2648: Enable ga4 in intergration and prod

---

deploy/template.yaml

Reverts govuk-one-login/ipv-cri-address-front#884

Revert "OJ-2648: Enable ga4 in intergration and prod"

---

deploy/template.yaml

Turns on GA4 in production 

---

.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml

[IPS-818] PR Title --> Ips 818 - upload action ecr updated to 1.2.6
post merge to build and post merge to dev updated with upload action ecr version 1.2.6. v was required with the newer version
updated to latest version
N/A
testing done in dev, see [IPS-818 ticket](https://govukverify.atlassian.net/jira/software/c/projects/IPS/boards/423?assignee=712020%3A6fb9db86-32cb-41ec-96b7-4148cd94dae4&selectedIssue=IPS-818) to view this
[IPS-818]: https://govukverify.atlassian.net/browse/IPS-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ips 818 - upload action ecr updated to 1.2.6

---

deploy/template.yaml

Reverts govuk-one-login/ipv-cri-address-front#888

Revert "Disables UA in staging"

---

package.json
yarn.lock

OJ-2674: Upgrade analytics package to include bug fix for GA4

OJ-2674: Upgrade analytics package

---

package.json
yarn.lock

OJ-2674: Upgrades common express

---

deploy/template.yaml

- Enable block WAF and associate with the load balancer
- Disable the count WAF which was deployed with the CloudFront
- Enable the block WAF 
- Associate the block with Load balancer
- Count WAF been added during CloudFront deployment.
- Having found CloudFront working, the count waf need to be disabled to enable the block WAF
- Disable the count association with Load balancer and enable the block waf association with load balancer
- Verify the CloudFront traffic using count WAF
- [IPS-863](https://govukverify.atlassian.net/browse/IPS-863)
[IPS-863]: https://govukverify.atlassian.net/browse/IPS-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-863: Enabled Block WAF Association with Load balancer

---

deploy/template.yaml
package.json
src/app.js
yarn.lock

Added `frontend-vital-signs` package and initialised it within`app.js`
Added metrics for the logging for `frontend-vital-signs`
The log messages provided by the frontend-vital-signs package is to help us monitor performance metrics such as average response times and how many requests we get per second. 
- [OJ-2760](https://govukverify.atlassian.net/browse/OJ-2760)
[OJ-2760]: https://govukverify.atlassian.net/browse/OJ-2760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2760: Add vital signs package

---

src/app/address/controllers/address/prepopulate.js
src/app/address/controllers/address/search.js
src/app/address/controllers/summary/confirm.js
src/lib/config.js

Add name parameter to hmpo-logger
Running trace-sync-io has uncovered the following places that we are blocking the event loop.
- [OJ-2891](https://govukverify.atlassian.net/browse/OJ-2891)
[OJ-2891]: https://govukverify.atlassian.net/browse/OJ-2891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2891: Add name parameter to hmpo-logger

---

package.json
yarn.lock

Upgrade dependencies
https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/53
- [OJ-2900](https://govukverify.atlassian.net/browse/OJ-2900)
[OJ-2900]: https://govukverify.atlassian.net/browse/OJ-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2900: Upgrade dependencies

---

package.json
yarn.lock

common express upgraded to 8.1.0
To include performance fix
- [OJ-2874](https://govukverify.atlassian.net/browse/OJ-2874)
[OJ-2874]: https://govukverify.atlassian.net/browse/OJ-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2874: Bump common express

---

src/app.js

Up maxEventLoopDelay as we're seeing quite a few 503s
Roughly 200 more 5xx errors than we saw this time last week even though traffic was about the same
- [OJ-2864](https://govukverify.atlassian.net/browse/OJ-2864)
[OJ-2864]: https://govukverify.atlassian.net/browse/OJ-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2864: Up maxEventLoopDelay as we're seeing quite a few 503s

---

deploy/template.yaml

Correct alarm description see: https://github.com/govuk-one-login/ipv-cri-address-front/pull/1032
[OJ-2872](https://govukverify.atlassian.net/browse/OJ-2872)
[OJ-2872]: https://govukverify.atlassian.net/browse/OJ-2872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2872: Correct Frontend Critical Alarm desc

---

deploy/template.yaml

Changed staging log level to debug
To debug international addresses issue in staging

Increase log level to debug international addresses issue in staging

---

src/app/address/controllers/address/nonUKAddress.js
src/app/address/controllers/address/prepopulate.js
src/app/address/controllers/address/whatCountry.js

Adds lots of log debug log messages
To try and debug the international addresses issue

Scatter gun logs messages

---

package.json
yarn.lock

Upgrade common express to version 10.0.1
To receive the latest fixes from common express
- [OJ-2977](https://govukverify.atlassian.net/browse/OJ-2977)
[OJ-2977]: https://govukverify.atlassian.net/browse/OJ-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2977: chore - upgrade common express v10.0.1

---

package.json
yarn.lock

Bump common express
To get extra logging for international addresses debugging
- [PYIC-7942](https://govukverify.atlassian.net/browse/PYIC-7942)
[PYIC-7942]: https://govukverify.atlassian.net/browse/PYIC-7942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7942: Bump common express

---

package.json
yarn.lock

BAU: Bump @govuk-one-login/frontend-vital-signs
New version measures max event loop delay rather than average which is more accurate when looking at overload protection

BAU: Bump @govuk-one-login/frontend-vital-signs

---

package.json
yarn.lock

Bump axios and wait-on, add form-data overrides
form-data vulnerability was fixed in axios 1.11.0 and wait-on 8.0.4
https://github.com/axios/axios/pull/6970
https://github.com/jeffbski/wait-on/pull/174
- [OJ-3271](https://govukverify.atlassian.net/browse/OJ-3271)
[OJ-3271]: https://govukverify.atlassian.net/browse/OJ-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3271: Bump axios and wait-on

---

package.json
yarn.lock

see: https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/89
- [OJ-3346](https://govukverify.atlassian.net/browse/OJ-3346)
[OJ-3346]: https://govukverify.atlassian.net/browse/OJ-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3346: Axios is vulnerable to DoS attack

---

deploy/template.yaml

Reverts govuk-one-login/ipv-cri-address-front#1251

Revert "OJ-3444: Added custom policy for inclusion in custom-managed policy"
